name: Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:

jobs:
  build:
    name: verify tests are passing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: set env
      id: set-env
      run: |
        echo "target branch: ${{ github.base_ref }}"
        case ${{ github.base_ref }} in 
          test) v=test ;;
          staging) v=staging ;;
          master) v=prod ;;
          dev) v=dev ;;
          *) v=not-found
        esac
        echo "name=env_name::canvas-$v" >> $GITHUB_OUTPUT
    - name: test env
      run: |
        echo "output is: ${{steps.set-env.outputs.name}}"

    - run: npm ci
    - run: npm test
