name: Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:

jobs:
  build:
    name: verify tests are passing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: set env
      id: set-env
      run: |
        echo "target branch: ${{ github.base_ref }}"
        if [ "${{ github.base_ref }}" = "test" ]; then
          echo "name=env_name::canvas-test" >> $GITHUB_OUTPUT
        elif [ "${{ github.base_ref }}" = "dev" ]; then
          echo "name=env_name::canvas-dev" >> $GITHUB_OUTPUT
        elif [ "${{ github.base_ref }}" = "staging" ]; then
          echo "name=env_name::canvas-staging" >> $GITHUB_OUTPUT
        elif [ "${{ github.base_ref }}" = "master" ]; then
          echo "name=env_name::canvas-prod" >> $GITHUB_OUTPUT
        else
          echo "name=env_name::not-found" >> $GITHUB_OUTPUT
        fi
    - name: test env
      run: |
        echo "output is: ${{steps.set-env.outputs.name}}"

    - run: npm ci
    - run: npm test
